// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/aleshkashell/pulumi-lxd/sdk/go/lxd/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Accept the server certificate
func GetAcceptRemoteCertificate(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "lxd:acceptRemoteCertificate")
}

// Deprecated: Use `lxd_remote.address` instead.
func GetAddress(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:address")
}

// The directory to look for existing LXD configuration. default = $HOME/snap/lxd/common/config:$HOME/.config/lxc
func GetConfigDir(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:configDir")
}
func GetGenerateClientCertificates(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "lxd:generateClientCertificates")
}
func GetLxdRemotes(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:lxdRemotes")
}

// Deprecated: Use `lxd_remote.port` instead.
func GetPort(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:port")
}

// The project where project-scoped resources will be created. Can be overridden in individual resources. default = default
func GetProject(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:project")
}

// How often to poll during state changes (default 10s)
func GetRefreshInterval(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:refreshInterval")
}

// Deprecated: Use `lxd_remote.name` instead.
func GetRemote(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:remote")
}

// Deprecated: Use `lxd_remote.password` instead.
func GetRemotePassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:remotePassword")
}

// Deprecated: Use `lxd_remote.scheme` instead.
func GetScheme(ctx *pulumi.Context) string {
	return config.Get(ctx, "lxd:scheme")
}
