// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ContainerDevice {
    name: string;
    properties: {[key: string]: any};
    type: string;
}

export interface ContainerFile {
    content?: string;
    createDirectories?: boolean;
    gid?: number;
    mode?: string;
    source?: string;
    targetFile: string;
    uid?: number;
}

export interface InstanceDevice {
    name: string;
    properties: {[key: string]: any};
    type: string;
}

export interface InstanceFile {
    content?: string;
    createDirectories?: boolean;
    gid?: number;
    mode?: string;
    source?: string;
    targetFile: string;
    uid?: number;
}

export interface ProfileDevice {
    name: string;
    properties: {[key: string]: any};
    type: string;
}

export namespace config {
    export interface LxdRemotes {
        address?: string;
        default?: boolean;
        name: string;
        password?: string;
        port?: string;
        scheme?: string;
    }

}
