// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PublishImage extends pulumi.CustomResource {
    /**
     * Get an existing PublishImage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PublishImageState, opts?: pulumi.CustomResourceOptions): PublishImage {
        return new PublishImage(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lxd:index/publishImage:PublishImage';

    /**
     * Returns true if the given object is an instance of PublishImage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PublishImage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PublishImage.__pulumiType;
    }

    public readonly aliases!: pulumi.Output<string[] | undefined>;
    public /*out*/ readonly architecture!: pulumi.Output<string>;
    public readonly compressionAlgorithm!: pulumi.Output<string | undefined>;
    public readonly container!: pulumi.Output<string>;
    public /*out*/ readonly createdAt!: pulumi.Output<number>;
    public readonly filename!: pulumi.Output<string | undefined>;
    public /*out*/ readonly fingerprint!: pulumi.Output<string>;
    public readonly project!: pulumi.Output<string | undefined>;
    public readonly properties!: pulumi.Output<{[key: string]: any} | undefined>;
    public readonly public!: pulumi.Output<boolean | undefined>;
    /**
     * A map of arbitrary strings that, when changed, will force the resource to be replaced.
     */
    public readonly triggers!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a PublishImage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PublishImageArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PublishImageArgs | PublishImageState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PublishImageState | undefined;
            resourceInputs["aliases"] = state ? state.aliases : undefined;
            resourceInputs["architecture"] = state ? state.architecture : undefined;
            resourceInputs["compressionAlgorithm"] = state ? state.compressionAlgorithm : undefined;
            resourceInputs["container"] = state ? state.container : undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["filename"] = state ? state.filename : undefined;
            resourceInputs["fingerprint"] = state ? state.fingerprint : undefined;
            resourceInputs["project"] = state ? state.project : undefined;
            resourceInputs["properties"] = state ? state.properties : undefined;
            resourceInputs["public"] = state ? state.public : undefined;
            resourceInputs["triggers"] = state ? state.triggers : undefined;
        } else {
            const args = argsOrState as PublishImageArgs | undefined;
            if ((!args || args.container === undefined) && !opts.urn) {
                throw new Error("Missing required property 'container'");
            }
            resourceInputs["aliases"] = args ? args.aliases : undefined;
            resourceInputs["compressionAlgorithm"] = args ? args.compressionAlgorithm : undefined;
            resourceInputs["container"] = args ? args.container : undefined;
            resourceInputs["filename"] = args ? args.filename : undefined;
            resourceInputs["project"] = args ? args.project : undefined;
            resourceInputs["properties"] = args ? args.properties : undefined;
            resourceInputs["public"] = args ? args.public : undefined;
            resourceInputs["triggers"] = args ? args.triggers : undefined;
            resourceInputs["architecture"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["fingerprint"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PublishImage.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering PublishImage resources.
 */
export interface PublishImageState {
    aliases?: pulumi.Input<pulumi.Input<string>[]>;
    architecture?: pulumi.Input<string>;
    compressionAlgorithm?: pulumi.Input<string>;
    container?: pulumi.Input<string>;
    createdAt?: pulumi.Input<number>;
    filename?: pulumi.Input<string>;
    fingerprint?: pulumi.Input<string>;
    project?: pulumi.Input<string>;
    properties?: pulumi.Input<{[key: string]: any}>;
    public?: pulumi.Input<boolean>;
    /**
     * A map of arbitrary strings that, when changed, will force the resource to be replaced.
     */
    triggers?: pulumi.Input<{[key: string]: any}>;
}

/**
 * The set of arguments for constructing a PublishImage resource.
 */
export interface PublishImageArgs {
    aliases?: pulumi.Input<pulumi.Input<string>[]>;
    compressionAlgorithm?: pulumi.Input<string>;
    container: pulumi.Input<string>;
    filename?: pulumi.Input<string>;
    project?: pulumi.Input<string>;
    properties?: pulumi.Input<{[key: string]: any}>;
    public?: pulumi.Input<boolean>;
    /**
     * A map of arbitrary strings that, when changed, will force the resource to be replaced.
     */
    triggers?: pulumi.Input<{[key: string]: any}>;
}
